import React, {useState} from "react"
import { useMultiSigWalletContext } from "../contexts/MultiSigWallet"
import { Button } from "semantic-ui-react"
import DepositForm from "./DepositForm"
import CreateTxModal from "./CreateTxModal"
